"""Assemble docs/curriculum/verification.md from the six probe results.

PRD Section 14: the report must record every probe's classification and
evidence, and the routine as a whole is blocked by Stage 0 if any probe
is inconclusive.
"""
from pathlib import Path
from typing import List

from src.curriculum.verification.types import STATUS_INCONCLUSIVE, ProbeResult

REPORT_TITLE = "# Stage 0 initial verification report\n"


def _render_probe(result: ProbeResult) -> str:
    lines = [
        f"## {result.probe_id}: {result.title}",
        "",
        f"**Status:** `{result.status}`",
        "",
        f"**Summary:** {result.summary}",
        "",
        "**Raw output:**",
        "",
        "```",
    ]
    lines += result.raw_output
    lines += ["```", ""]
    return "\n".join(lines)


def render_report(results: List[ProbeResult]) -> str:
    any_inconclusive = any(r.status == STATUS_INCONCLUSIVE for r in results)
    header = [
        REPORT_TITLE,
        "Generated by the Stage 0 verification routine, PRD Section 14. "
        "Runs all six probes without aborting on the first failure.",
        "",
        f"**Overall gate: {'BLOCKED (inconclusive result present)' if any_inconclusive else 'PASSED (no inconclusive result)'}**",
        "",
        "| Probe | Status |",
        "|---|---|",
    ]
    for result in results:
        header.append(f"| {result.probe_id} | `{result.status}` |")
    header.append("")

    body = [_render_probe(result) for result in results]
    return "\n".join(header) + "\n" + "\n".join(body)


def write_report(results: List[ProbeResult], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = render_report(results)
    output_path.write_text(content, encoding="utf-8")
